version: "3"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app # Montre le répertoire local dans le conteneur
      - /usr/src/app/node_modules # Exclure node_modules du volume
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run dev # Utilise le script nodemon pour démarrer
    environment:
      - NODE_ENV=development

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
