# Utilise une image de base officielle Node.js
FROM node:16

# Crée un répertoire de travail pour l'application
WORKDIR /usr/src/app

# Copie les fichiers package.json et package-lock.json (si présent)
COPY package*.json ./

# Installe les dépendances de l'application
RUN npm install

# Copie le reste du code de l'application
COPY . .

# Expose le port que l'application utilise
EXPOSE 3000

# Commande pour démarrer l'application
CMD [ "node", "src/app.js" ]